server:
  port: 8080
  servlet:
    context-path: /takeout

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/takeout?&serverTimezone=Asia/Shanghai
    username: root
    password: ******
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update

#logging:
#  level:
#    com:
#      springboot:
#        mapper: debug